# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import common_messages_pb2 as common__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63lient_service.proto\x12\x11shopping_platform\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15\x63ommon_messages.proto2Y\n\rClientService\x12H\n\x0cnotifyClient\x12\x1e.shopping_platform.ItemDetails\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_CLIENTSERVICE = DESCRIPTOR.services_by_name['ClientService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTSERVICE._serialized_start=95
  _CLIENTSERVICE._serialized_end=184
# @@protoc_insertion_point(module_scope)
