# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\x11\n\x0fRequestVoteArgs\"\x12\n\x10RequestVoteReply\"\x13\n\x11\x41ppendEntriesArgs\"\x14\n\x12\x41ppendEntriesReply2\x8f\x01\n\x0bRaftService\x12\x42\n\rAppendEntries\x12\x17.raft.AppendEntriesArgs\x1a\x18.raft.AppendEntriesReply\x12<\n\x0bRequestVote\x12\x15.raft.RequestVoteArgs\x1a\x16.raft.RequestVoteReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEARGS']._serialized_start=20
  _globals['_REQUESTVOTEARGS']._serialized_end=37
  _globals['_REQUESTVOTEREPLY']._serialized_start=39
  _globals['_REQUESTVOTEREPLY']._serialized_end=57
  _globals['_APPENDENTRIESARGS']._serialized_start=59
  _globals['_APPENDENTRIESARGS']._serialized_end=78
  _globals['_APPENDENTRIESREPLY']._serialized_start=80
  _globals['_APPENDENTRIESREPLY']._serialized_end=100
  _globals['_RAFTSERVICE']._serialized_start=103
  _globals['_RAFTSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
