# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/reducer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/reducer.proto\x12\tMapReduce\"U\n\rReduceRequest\x12\r\n\x05query\x18\x01 \x01(\x05\x12\x1c\n\x14partition_files_path\x18\x02 \x03(\t\x12\x17\n\x0foutput_location\x18\x03 \x01(\t\"\x7f\n\x0eReduceResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .MapReduce.ReduceResponse.Status\x12\x18\n\x10output_file_path\x18\x02 \x01(\t\"!\n\x06Status\x12\n\n\x06\x46\x41ILED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x32Q\n\x0eReducerService\x12?\n\x06reduce\x12\x18.MapReduce.ReduceRequest\x1a\x19.MapReduce.ReduceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.reducer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REDUCEREQUEST']._serialized_start=35
  _globals['_REDUCEREQUEST']._serialized_end=120
  _globals['_REDUCERESPONSE']._serialized_start=122
  _globals['_REDUCERESPONSE']._serialized_end=249
  _globals['_REDUCERESPONSE_STATUS']._serialized_start=216
  _globals['_REDUCERESPONSE_STATUS']._serialized_end=249
  _globals['_REDUCERSERVICE']._serialized_start=251
  _globals['_REDUCERSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
