# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_messages_pb2 as common__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='master.proto',
  package='MapReduce',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmaster.proto\x12\tMapReduce\x1a\x15\x63ommon_messages.proto\"%\n\x10SubmitMapJobArgs\x12\x11\n\tworker_id\x18\x01 \x01(\x05\"\x10\n\x0eSubmitMapReply\"(\n\x13SubmitReduceJobArgs\x12\x11\n\tworker_id\x18\x01 \x01(\x05\"\x13\n\x11SubmitReduceReply2\xa9\x01\n\x0eMasterServices\x12\x46\n\x0cSubmitMapJob\x12\x1b.MapReduce.SubmitMapJobArgs\x1a\x19.MapReduce.SubmitMapReply\x12O\n\x0fSubmitReduceJob\x12\x1e.MapReduce.SubmitReduceJobArgs\x1a\x1c.MapReduce.SubmitReduceReplyb\x06proto3')
  ,
  dependencies=[common__messages__pb2.DESCRIPTOR,])




_SUBMITMAPJOBARGS = _descriptor.Descriptor(
  name='SubmitMapJobArgs',
  full_name='MapReduce.SubmitMapJobArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='MapReduce.SubmitMapJobArgs.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=87,
)


_SUBMITMAPREPLY = _descriptor.Descriptor(
  name='SubmitMapReply',
  full_name='MapReduce.SubmitMapReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=105,
)


_SUBMITREDUCEJOBARGS = _descriptor.Descriptor(
  name='SubmitReduceJobArgs',
  full_name='MapReduce.SubmitReduceJobArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_id', full_name='MapReduce.SubmitReduceJobArgs.worker_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=147,
)


_SUBMITREDUCEREPLY = _descriptor.Descriptor(
  name='SubmitReduceReply',
  full_name='MapReduce.SubmitReduceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['SubmitMapJobArgs'] = _SUBMITMAPJOBARGS
DESCRIPTOR.message_types_by_name['SubmitMapReply'] = _SUBMITMAPREPLY
DESCRIPTOR.message_types_by_name['SubmitReduceJobArgs'] = _SUBMITREDUCEJOBARGS
DESCRIPTOR.message_types_by_name['SubmitReduceReply'] = _SUBMITREDUCEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmitMapJobArgs = _reflection.GeneratedProtocolMessageType('SubmitMapJobArgs', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITMAPJOBARGS,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:MapReduce.SubmitMapJobArgs)
  ))
_sym_db.RegisterMessage(SubmitMapJobArgs)

SubmitMapReply = _reflection.GeneratedProtocolMessageType('SubmitMapReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITMAPREPLY,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:MapReduce.SubmitMapReply)
  ))
_sym_db.RegisterMessage(SubmitMapReply)

SubmitReduceJobArgs = _reflection.GeneratedProtocolMessageType('SubmitReduceJobArgs', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITREDUCEJOBARGS,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:MapReduce.SubmitReduceJobArgs)
  ))
_sym_db.RegisterMessage(SubmitReduceJobArgs)

SubmitReduceReply = _reflection.GeneratedProtocolMessageType('SubmitReduceReply', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITREDUCEREPLY,
  __module__ = 'master_pb2'
  # @@protoc_insertion_point(class_scope:MapReduce.SubmitReduceReply)
  ))
_sym_db.RegisterMessage(SubmitReduceReply)



_MASTERSERVICES = _descriptor.ServiceDescriptor(
  name='MasterServices',
  full_name='MapReduce.MasterServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=171,
  serialized_end=340,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitMapJob',
    full_name='MapReduce.MasterServices.SubmitMapJob',
    index=0,
    containing_service=None,
    input_type=_SUBMITMAPJOBARGS,
    output_type=_SUBMITMAPREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitReduceJob',
    full_name='MapReduce.MasterServices.SubmitReduceJob',
    index=1,
    containing_service=None,
    input_type=_SUBMITREDUCEJOBARGS,
    output_type=_SUBMITREDUCEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERSERVICES)

DESCRIPTOR.services_by_name['MasterServices'] = _MASTERSERVICES

# @@protoc_insertion_point(module_scope)
