# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_pb2 as master__pb2


class MasterServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitMapJob = channel.unary_unary(
                '/MapReduce.MasterServices/SubmitMapJob',
                request_serializer=master__pb2.SubmitMapJobArgs.SerializeToString,
                response_deserializer=master__pb2.SubmitMapReply.FromString,
                )
        self.SubmitReduceJob = channel.unary_unary(
                '/MapReduce.MasterServices/SubmitReduceJob',
                request_serializer=master__pb2.SubmitReduceJobArgs.SerializeToString,
                response_deserializer=master__pb2.SubmitReduceReply.FromString,
                )


class MasterServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitMapJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitReduceJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitMapJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMapJob,
                    request_deserializer=master__pb2.SubmitMapJobArgs.FromString,
                    response_serializer=master__pb2.SubmitMapReply.SerializeToString,
            ),
            'SubmitReduceJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitReduceJob,
                    request_deserializer=master__pb2.SubmitReduceJobArgs.FromString,
                    response_serializer=master__pb2.SubmitReduceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MapReduce.MasterServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitMapJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MapReduce.MasterServices/SubmitMapJob',
            master__pb2.SubmitMapJobArgs.SerializeToString,
            master__pb2.SubmitMapReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitReduceJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MapReduce.MasterServices/SubmitReduceJob',
            master__pb2.SubmitReduceJobArgs.SerializeToString,
            master__pb2.SubmitReduceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
