# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import master_pb2 as master__pb2


class MasterServicesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubmitMapJob = channel.unary_unary(
        '/MapReduce.MasterServices/SubmitMapJob',
        request_serializer=master__pb2.SubmitMapJobArgs.SerializeToString,
        response_deserializer=master__pb2.SubmitMapReply.FromString,
        )
    self.SubmitReduceJob = channel.unary_unary(
        '/MapReduce.MasterServices/SubmitReduceJob',
        request_serializer=master__pb2.SubmitReduceJobArgs.SerializeToString,
        response_deserializer=master__pb2.SubmitReduceReply.FromString,
        )


class MasterServicesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubmitMapJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubmitReduceJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MasterServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubmitMapJob': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitMapJob,
          request_deserializer=master__pb2.SubmitMapJobArgs.FromString,
          response_serializer=master__pb2.SubmitMapReply.SerializeToString,
      ),
      'SubmitReduceJob': grpc.unary_unary_rpc_method_handler(
          servicer.SubmitReduceJob,
          request_deserializer=master__pb2.SubmitReduceJobArgs.FromString,
          response_serializer=master__pb2.SubmitReduceReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MapReduce.MasterServices', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
