# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reducer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_messages_pb2 as common__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreducer.proto\x12\tMapReduce\x1a\x15\x63ommon_messages.proto\"=\n\x10\x44oReduceTaskArgs\x12\x11\n\treduce_id\x18\x01 \x01(\x05\x12\x16\n\x0emapper_address\x18\x02 \x03(\t\"=\n\x08\x43\x65ntroid\x12\r\n\x05index\x18\x01 \x01(\x05\x12\"\n\x08\x63\x65ntroid\x18\x02 \x01(\x0b\x32\x10.MapReduce.Point\"f\n\x11\x44oReduceTaskReply\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.MapReduce.Status\x12.\n\x11updated_centroids\x18\x02 \x03(\x0b\x32\x13.MapReduce.Centroid*!\n\x06Status\x12\n\n\x06\x46\x41ILED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x32Y\n\x0eReducerService\x12G\n\x08\x44oReduce\x12\x1b.MapReduce.DoReduceTaskArgs\x1a\x1c.MapReduce.DoReduceTaskReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reducer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=281
  _globals['_STATUS']._serialized_end=314
  _globals['_DOREDUCETASKARGS']._serialized_start=51
  _globals['_DOREDUCETASKARGS']._serialized_end=112
  _globals['_CENTROID']._serialized_start=114
  _globals['_CENTROID']._serialized_end=175
  _globals['_DOREDUCETASKREPLY']._serialized_start=177
  _globals['_DOREDUCETASKREPLY']._serialized_end=279
  _globals['_REDUCERSERVICE']._serialized_start=316
  _globals['_REDUCERSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
