# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import reducer_pb2 as reducer__pb2


class ReducerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoReduce = channel.unary_unary(
        '/MapReduce.ReducerService/DoReduce',
        request_serializer=reducer__pb2.DoReduceTaskArgs.SerializeToString,
        response_deserializer=reducer__pb2.DoReduceTaskReply.FromString,
        )


class ReducerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoReduce(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReducerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoReduce': grpc.unary_unary_rpc_method_handler(
          servicer.DoReduce,
          request_deserializer=reducer__pb2.DoReduceTaskArgs.FromString,
          response_serializer=reducer__pb2.DoReduceTaskReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MapReduce.ReducerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
